# -*- coding: utf-8 -*-
"""IBM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O6wtvNZRVSHpWBHN-BgcTliJtkfP1Q1r
"""

!pip install CurrencyConverter
from currency_converter import CurrencyConverter
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.options.mode.chained_assignment = None  # default='warn'

cc = CurrencyConverter()

from google.colab import drive
drive.mount('/content/drive/')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/My Drive/IBM/

df = pd.read_csv("/content/drive/MyDrive/IBM/HI-Medium_Trans.csv")

df.isnull().values.any()

df['Payment Currency'].unique()

df['Payment Currency'] = df['Payment Currency'].astype(str)
df['Receiving Currency'] = df['Receiving Currency'].astype(str)

df['Payment Currency'].replace({'Bitcoin': 'BTC', 'US Dollar': 'USD','UK Pound':'GBP', 'Canadian Dollar':'CAD','Australian Dollar': 'AUD','Swiss Franc' :'CHF', 'Yen': 'JPY', 'Yuan': 'CNY', 'Rupee': 'INR','Mexican Peso': 'MXN','Ruble': 'RUB','Saudi Riyal': 'SAR','Brazil Real': 'BRL','Shekel': 'ILS', 'Euro' :'EUR' }, inplace=True)
df['Receiving Currency'].replace({'Bitcoin': 'BTC', 'US Dollar': 'USD','UK Pound':'GBP', 'Canadian Dollar':'CAD','Australian Dollar': 'AUD','Swiss Franc' :'CHF', 'Yen': 'JPY', 'Yuan': 'CNY', 'Rupee': 'INR','Mexican Peso': 'MXN','Ruble': 'RUB','Saudi Riyal': 'SAR','Brazil Real': 'BRL','Shekel': 'ILS', 'Euro' :'EUR' }, inplace=True)

df['Payment Currency'].unique()
df['Receiving Currency'].unique()

df

def convert_to_usd(amount, currency):
    if currency == 'BTC':
        return amount * 69138
    if currency == 'SAR':
        return amount * 0.27
    else:
        return cc.convert(amount, currency, 'USD')

df['Amount Received USD'] = df.apply(lambda row: convert_to_usd(row['Amount Received'], row['Receiving Currency']), axis=1)

df.isnull().values.any()

def convert_to_usd(amount, currency):
    if currency == 'BTC':
        return amount * 69138
    if currency == 'SAR':
        return amount * 0.27
    else:
        return cc.convert(amount, currency, 'USD')
df['Amount Paid USD'] = df.apply(lambda row: convert_to_usd(row['Amount Paid'], row['Payment Currency']), axis=1)

df.isnull().values.any()

df

"""The accurate bitcoin conversion wasn't available so the USD conversion of bitcoin currency has become NAN"""



#df = df.drop('Receiving Currency' , axis=1)
#df = df.drop('Payment Currency' , axis=1)
df = df.drop('Amount Received', axis=1)
df = df.drop('Amount Paid' , axis=1)

df

df.to_csv('CLEANED_HI-MEDIUM_TRANS.csv', index=False)

"""So thats like almost 14k NAN values"""

